sudo: false
language: python
python:
  - "2.7"
virtualenv:
    system_site_packages: true
cache:
  apt: true
  pip: true
  directories:
  - rdkit
addons:
  apt_packages:
  - git
  - build-essential
  - gfortran
  - python-dev
  - liblapack-dev
  - python-openbabel
  - python-setuptools
  - python-pip
  - python-numpy
  - python-scipy
  - python-matplotlib
  # for RDKit
  - flex bison
  - build-essential
  - python-numpy
  - cmake
  - python-dev
  - sqlite3
  - libsqlite3-dev
  - libboost-dev
  - libboost-python-dev
  - libboost-regex-dev
  - python-imaging
  - openjdk-7-jdk
  - swig
  - junit
before_install:
  - cd ..
  - git clone https://github.com/GreenGroup/RMG-database.git
  - git clone https://github.com/GreenGroup/PyDAS.git
  - git clone https://github.com/GreenGroup/PyDQED.git
  # RDKit, based on https://github.com/rdkit/rdkit/blob/master/.travis.yml
  # - sudo apt-get install -qq flex bison build-essential python-numpy cmake python-dev sqlite3 libsqlite3-dev libboost-dev libboost-python-dev libboost-regex-dev python-imaging openjdk-7-jdk swig junit
  - export CXX=g++
  - export CC=gcc
  - git clone https://github.com/rdkit/rdkit.git
  - cd rdkit
  - export RDBASE=`pwd`
  - export PYTHONPATH=${PYTHONPATH}:${RDBASE}
  - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${RDBASE}/lib
  - cd External/INCHI-API
  - ./download-inchi.sh
  - cd ../../
  - mkdir -p build
  - cd build
  - mkdir -p $RDBASE/External/java_lib
  - cp /usr/share/java/junit.jar $RDBASE/External/java_lib
  - ls -l $RDBASE/External/java_lib
  - cmake .. -DRDK_BUILD_INCHI_SUPPORT=ON
  - make -j2
  - make install
  - cd ..
  - cd ..
install:
  - cd $TRAVIS_BUILD_DIR
  - pip install --upgrade numpy
  - pip install --upgrade -r requirements.txt
  - cd ..
  - cd PyDAS
  - cd daspk31
  - wget http://www.engineering.ucsb.edu/~cse/Software/daspk31.tgz
  - cd ..
  - make F77=gfortran
  - make install
  - cd ..
  - cd PyDQED
  - make F77=gfortran
  - make install
  - cd ..
  - cd $TRAVIS_BUILD_DIR
  - make noQM
script: 
  - make test
  - make eg1
