# For conda build
package:
  name: rmg
  version: "0" # set by build.sh, which gets from rmgpy/__init__.py

source:
  path: .

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - argparse # [py26]
    - boost ==1.56.0
    - cairo
    - cairocffi
    - coverage
    - cython ==0.21
    - gcc # [unix]
    - gprof2dot
    - guppy
    - jinja2
    - libgcc # [unix]
    - markupsafe
    - matplotlib
    - nose
    - numpy
    - openbabel
    - psutil
    - pydas >=1.0.1
    - pydot
    - pydqed
    - pyparsing
    - python
    - quantities
    - rdkit
    - rdkit ==2015.03.1
    - scipy
    - setuptools
    - xlwt

  run:
    - argparse # [py26]
    - cairo
    - cairocffi
    - coverage
    - cython ==0.21
    - gprof2dot
    - graphviz
    - guppy
    - jinja2
    - libgcc # [unix]
    - markupsafe
    - matplotlib
    - mopac
    - nose
    - numpy
    - openbabel
    - psutil
    - pydas >=1.0.1
    - pydot
    - pydqed
    - pyparsing
    - python
    - quantities
    - rdkit ==2015.03.1
    - scipy
    - symmetry
    - xlwt

test:
  requires:
    - nose
  imports:
    - rmgpy
  commands:
    - make -C $SRC_DIR test

about:
  home: http://github.com/ReactionMechanismGenerator/RMG-Py
  license: MIT
  summary: "A program for automatically generating kinetic models of chemical reaction mechanisms."
