# For conda build
package:
  name: rmg
  version: "0" # set by build.sh, which gets from rmgpy/__init__.py

source:
  path: .

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - gcc # [unix]
    - python
    - setuptools
    - cython ==0.21
    - numpy
    - pydas >=1.0.1
    - pydqed
    - boost ==1.56.0
    - rdkit
    - libgcc # [unix]
    - numpy
    - matplotlib
    - rdkit ==2015.03.1
    - quantities
    - scipy
    - xlwt
    - markupsafe
    - jinja2
    - argparse # [py26]
    - pyparsing
    - pydot
    - nose
    - coverage
    - guppy
    - gprof2dot
    - cairo
    - cairocffi
    - openbabel
    - psutil
  run:
    - libgcc # [unix]
    - python
    - numpy
    - cython ==0.21
    - matplotlib
    - rdkit ==2015.03.1
    - pydas >=1.0.1
    - pydqed
    - quantities
    - scipy
    - xlwt
    - markupsafe
    - jinja2
    - argparse # [py26]
    - pyparsing
    - pydot
    - nose
    - coverage
    - guppy
    - gprof2dot
    - cairo
    - cairocffi
    - openbabel
    - psutil
    - symmetry
    - mopac
    - graphviz
test:
  requires:
    - nose
  imports:
    - rmgpy
  commands:
    - make -C $SRC_DIR test

about:
  home: http://github.com/ReactionMechanismGenerator/RMG-Py
  license: MIT
  summary: "A program for automatically generating kinetic models of chemical reaction mechanisms."
